/* eslint-disable */
// Generated by Wrangler by running `wrangler types db/bindings.d.ts --include-runtime false` (hash: 0f82e77b092138dacc110c12cdb0da9b)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
	ACCESS_TEAM_DOMAIN: "https://floral-dust-91a4.cloudflareaccess.com";
	ACCESS_AUD: "e6c6a92c40cb0e2f2b8f95d67ba7394d15d41bf54b6b0d95f84b0f1fbb156f9a";
	CREDENTIAL_ENCRYPTION_KEY: string;
	DEV_USER_EMAIL: string;
	SYNC_ACCOUNTS: Service /* entrypoint AccountAdmin from dictation-operative-sync */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "CREDENTIAL_ENCRYPTION_KEY" | "DEV_USER_EMAIL">> {}
}
