import AppKit
import ImageIO
import UniformTypeIdentifiers

@MainActor
struct MacClipboardAdapter {
  let board: NSPasteboard
  init(board: NSPasteboard = .general) { self.board = board }
  static let receivedMarker = NSPasteboard.PasteboardType("org.dictation.sync.received")
  var changeCount: Int { board.changeCount }
  var isAutomaticExcluded: Bool {
    let types = board.types ?? []
    return [
      Self.receivedMarker, .init("org.nspasteboard.TransientType"),
      .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.AutoGeneratedType"),
    ].contains(where: types.contains)
  }
  func read() throws -> SyncPayload {
    guard !(board.types ?? []).contains(.fileURL) else {
      throw SyncFailure("Copied files are not image content. Open the image and copy its pixels.")
    }
    if let png = board.data(forType: .png) { return try validatedImage(png) }
    if let tiff = board.data(forType: .tiff) {
      guard tiff.count <= SyncPayload.imageLimit * 4,
        let source = CGImageSourceCreateWithData(tiff as CFData, nil),
        let info = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
        let w = info[kCGImagePropertyPixelWidth] as? Int,
        let h = info[kCGImagePropertyPixelHeight] as? Int, w > 0, h > 0, w <= 16384, h <= 16384,
        w * h <= 40_000_000, let image = CGImageSourceCreateImageAtIndex(source, 0, nil)
      else { throw SyncFailure("Unsupported image or image exceeds 40 megapixels.") }
      let output = NSMutableData()
      guard
        let destination = CGImageDestinationCreateWithData(
          output, UTType.png.identifier as CFString, 1, nil)
      else { throw SyncFailure("PNG conversion unavailable.") }
      CGImageDestinationAddImage(destination, image, nil)
      guard CGImageDestinationFinalize(destination) else {
        throw SyncFailure("Image conversion failed.")
      }
      return try validatedImage(output as Data)
    }
    guard let text = board.string(forType: .string), !text.isEmpty else {
      throw SyncFailure("Copy text or an image first.")
    }
    let payload = SyncPayload(mime: "text/plain", bytes: Data(text.utf8))
    try payload.validate()
    return payload
  }
  private func validatedImage(_ data: Data) throws -> SyncPayload {
    let payload = SyncPayload(mime: "image/png", bytes: data)
    try payload.validate()
    guard let source = CGImageSourceCreateWithData(data as CFData, nil),
      CGImageSourceCreateImageAtIndex(source, 0, nil) != nil
    else { throw SyncFailure("This image could not be decoded.") }
    return payload
  }
  func write(_ payload: SyncPayload, expectedCount: Int) throws {
    try payload.validate()
    guard board.changeCount == expectedCount else {
      throw SyncFailure(
        "Your clipboard changed during the transfer. Receive latest again when ready.")
    }
    let item = NSPasteboardItem()
    if payload.mime == "image/png" {
      _ = try validatedImage(payload.bytes)
      item.setData(payload.bytes, forType: .png)
    } else {
      item.setString(String(decoding: payload.bytes, as: UTF8.self), forType: .string)
    }
    item.setData(Data(), forType: Self.receivedMarker)
    board.clearContents()
    guard board.writeObjects([item]) else { throw SyncFailure("Could not write the clipboard.") }
  }
}
